debug:
  false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.study.projectboard: debug
    org.springframework.web.servlet: debug

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/board
    username: board
    password: board
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

  data.rest:
    base-path: /api
    detection-strategy: annotated

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always

  data:
    rest:
      base-path: /api
      detection-strategy: annotated

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:board;mode=mysql;
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always

